import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../containers/navbar'
import Header from '../containers/header'
import Logos from '../containers/logos'
import Excontainer from '../containers/excontainer'
import Excollections from '../containers/excollections'
import Topsellers from '../containers/topsellers'
import About from '../containers/about'
import Subscribe from '../containers/subscribe'
import Footer from '../containers/footer'

export default function Home() {
  return (
    <div className={styles.Home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true'/>
        <link href="https://fonts.googleapis.com/css2?family=Aldrich&family=Inter:wght@400;500;800&family=MuseoModerno&family=Orbitron:wght@700&family=Rajdhani:wght@400;500;600;700&family=Roboto:wght@400;500&family=Spartan:wght@600&display=swap" rel="stylesheet"/>
      </Head>

      <Navbar />
      <Header />
      <Logos />
      <Excontainer nftcard />
      <Excollections />
      <Excontainer profilecard/>
      <Topsellers />
      <About />
      <Subscribe />
      <Footer />
    </div>
  )
}
